//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderNumber { get; set; }
        public int UserId { get; set; }
        public decimal Total { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool Valid { get; set; }
        public Nullable<System.DateTime> InvalidDate { get; set; }
    }
}
